[package]
name = "gemu"
version = "0.1.0"
authors = ["George Roger <georger@xmos.com>"]

[dependencies]
gb_emu = { path = "gb_emu" }
gb_synth = { path = "../gb_synth" }
sdl2 = "0.31.0"

[profile.release]
lto = true
